import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f9fafb',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: '#ffffff',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1f2937',
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingVertical: 16,
        gap: 20,
    },
    processingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 16,
    },
    processingText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1f2937',
    },
    processingSubtext: {
        fontSize: 14,
        color: '#6b7280',
    },
    successContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 12,
    },
    successIcon: {
        marginBottom: 12,
    },
    successTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#16a34a',
    },
    successText: {
        fontSize: 16,
        color: '#1f2937',
        textAlign: 'center',
    },
    successSubtext: {
        fontSize: 14,
        color: '#6b7280',
    },
    summaryCard: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        overflow: 'hidden',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    summaryHeader: {
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 8,
    },
    summaryTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#1f2937',
    },
    packageImage: {
        width: '100%',
        height: 120,
        backgroundColor: '#e5e7eb',
    },
    summaryDetails: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        gap: 8,
    },
    summaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    detailLabel: {
        fontSize: 13,
        color: '#6b7280',
    },
    detailLabelTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1f2937',
    },
    detailValue: {
        fontSize: 13,
        fontWeight: '600',
        color: '#1f2937',
    },
    divider: {
        height: 1,
        backgroundColor: '#e5e7eb',
        marginVertical: 4,
    },
    totalLabel: {
        fontSize: 14,
        fontWeight: '700',
        color: '#1f2937',
    },
    totalValue: {
        fontSize: 16,
        fontWeight: '700',
        color: '#6366f1',
    },
    methodsSection: {
        gap: 12,
    },
    methodsTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1f2937',
    },
    methodButton: {
        flexDirection: 'row',
        backgroundColor: '#ffffff',
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderWidth: 2,
        borderColor: '#e5e7eb',
        alignItems: 'center',
        gap: 12,
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },
    methodButtonSelected: {
        borderColor: '#6366f1',
        backgroundColor: '#f0f4ff',
    },
    methodIcon: {
        width: 48,
        height: 48,
        borderRadius: 8,
        backgroundColor: '#f3f4f6',
        justifyContent: 'center',
        alignItems: 'center',
    },
    methodIconText: {
        fontSize: 24,
    },
    methodInfo: {
        flex: 1,
    },
    methodName: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1f2937',
        marginBottom: 2,
    },
    methodDescription: {
        fontSize: 12,
        color: '#6b7280',
    },
    methodRadio: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#d1d5db',
    },
    methodRadioSelected: {
        backgroundColor: '#6366f1',
        borderColor: '#6366f1',
    },
    termsContainer: {
        flexDirection: 'row',
        backgroundColor: '#f3f4f6',
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 8,
        gap: 8,
        alignItems: 'flex-start',
    },
    termsText: {
        fontSize: 12,
        color: '#6b7280',
        flex: 1,
        lineHeight: 16,
    },
    errorContainer: {
        flexDirection: 'row',
        backgroundColor: '#fee2e2',
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 8,
        gap: 8,
        alignItems: 'flex-start',
    },
    errorText: {
        fontSize: 12,
        color: '#dc2626',
        flex: 1,
        lineHeight: 16,
    },
    actionContainer: {
        paddingHorizontal: 16,
        paddingVertical: 16,
        borderTopWidth: 1,
        borderTopColor: '#e5e7eb',
        backgroundColor: '#ffffff',
    },
    paymentButton: {
        flexDirection: 'row',
        backgroundColor: '#6366f1',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    disabledButton: {
        opacity: 0.6,
    },
    paymentButtonText: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: '700',
    },
    avatarSection: {
        alignItems: 'center',
        marginVertical: 20,
    },
    avatar: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#d1d5db',
    },
    avatarPlaceholder: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#e5e7eb',
        justifyContent: 'center',
        alignItems: 'center',
    },
    editAvatarButton: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#6366f1',
        justifyContent: 'center',
        alignItems: 'center',
    },
    formSection: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 16,
        marginBottom: 16,
        gap: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    formGroup: {
        gap: 8,
    },
    label: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1f2937',
    },
    input: {
        borderWidth: 1,
        borderColor: '#d1d5db',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 14,
        color: '#1f2937',
        backgroundColor: '#ffffff',
    },
    inputDisabled: {
        backgroundColor: '#f3f4f6',
        color: '#6b7280',
    },
    statsSection: {
        gap: 12,
        marginBottom: 16,
    },
    statCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 16,
        gap: 12,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    statCardIcon: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#f3f4f6',
        justifyContent: 'center',
        alignItems: 'center',
    },
    statCardContent: {
        flex: 1,
    },
    statCardLabel: {
        fontSize: 12,
        color: '#6b7280',
        marginBottom: 2,
    },
    statCardValue: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1f2937',
    },
    mainButton: {
        flexDirection: 'row',
        backgroundColor: '#6366f1',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        marginBottom: 8,
    },
    mainButtonText: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: '600',
    },
    cancelButton: {
        backgroundColor: '#e5e7eb',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
        marginBottom: 16,
    },
    cancelButtonText: {
        color: '#1f2937',
        fontSize: 16,
        fontWeight: '600',
    },
    accountSection: {
        marginTop: 20,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1f2937',
        marginBottom: 12,
    },
    settingItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        paddingHorizontal: 16,
        paddingVertical: 12,
        marginBottom: 8,
        borderRadius: 8,
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },
    settingItemLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    settingItemText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#1f2937',
    },
    settingItemValue: {
        fontSize: 14,
        color: '#6b7280',
    },
    logoutButton: {
        flexDirection: 'row',
        backgroundColor: '#fee2e2',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        marginTop: 20,
    },
    logoutButtonText: {
        color: '#ef4444',
        fontSize: 16,
        fontWeight: '600',
    },
    welcomeSection: {
        backgroundColor: '#6366f1',
        paddingHorizontal: 16,
        paddingVertical: 20,
        gap: 16,
        borderRadius: 12,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    welcomeText: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.8)',
    },
    userName: {
        fontSize: 24,
        fontWeight: '700',
        color: '#ffffff',
    },
    userStats: {
        flexDirection: 'row',
        gap: 20,
    },
    statItem: {
        alignItems: 'center',
        gap: 4,
    },
    statValue: {
        fontSize: 18,
        fontWeight: '700',
        color: '#ffffff',
    },
    statLabel: {
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.8)',
    },
    section: {
        marginTop: 24,
        paddingHorizontal: 16,
    },
    sectionCard: {
        marginTop: 24,
        paddingHorizontal: 0,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    viewAll: {
        fontSize: 14,
        color: '#6366f1',
        fontWeight: '600',
    },
    packageCard: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        overflow: 'hidden',
        marginBottom: 12,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    packageContent: {
        padding: 12,
    },
    packageHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 8,
        gap: 8,
    },
    packageTitle: {
        flex: 1,
        fontSize: 14,
        fontWeight: '700',
        color: '#1f2937',
    },
    priceBadge: {
        backgroundColor: '#dbeafe',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    priceText: {
        color: '#0284c7',
        fontSize: 12,
        fontWeight: '600',
    },
    packageDescription: {
        fontSize: 12,
        color: '#6b7280',
        marginBottom: 8,
    },
    packageMeta: {
        flexDirection: 'row',
        gap: 12,
    },
    metaItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    metaText: {
        fontSize: 12,
        color: '#6b7280',
    },
    rankingsList: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        overflow: 'hidden',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    rankingItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
        gap: 12,
    },
    rankBadge: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#fef3c7',
        justifyContent: 'center',
        alignItems: 'center',
    },
    rankText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#92400e',
    },
    userAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#d1d5db',
    },
    rankingContent: {
        flex: 1,
    },
    rankingName: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1f2937',
        marginBottom: 2,
    },
    rankingPoints: {
        fontSize: 12,
        color: '#6b7280',
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: 16,
        marginVertical: 12,
        paddingHorizontal: 12,
        backgroundColor: '#ffffff',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    searchInput: {
        flex: 1,
        paddingVertical: 10,
        paddingHorizontal: 8,
        fontSize: 14,
        color: '#1f2937',
    },
    filterTabs: {
        flexDirection: 'row',
        paddingHorizontal: 16,
        paddingBottom: 12,
        gap: 8,
    },
    filterTab: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 6,
        backgroundColor: '#e5e7eb',
    },
    filterTabActive: {
        backgroundColor: '#6366f1',
    },
    filterTabText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#6b7280',
    },
    filterTabTextActive: {
        color: '#ffffff',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    listContent: {
        paddingHorizontal: 16,
        paddingBottom: 20,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 12,
    },
    emptyText: {
        fontSize: 16,
        color: '#6b7280',
        fontWeight: '500',
    },
    titleContainer: {
        flex: 1,
        gap: 8,
    },
    difficultyBadge: {
        alignSelf: 'flex-start',
    },
    difficultyText: {
        fontSize: 11,
        fontWeight: '600',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
        overflow: 'hidden',
    },
    difficultyEasy: {
        backgroundColor: '#dcfce7',
        color: '#166534',
    },
    difficultyMedium: {
        backgroundColor: '#fef3c7',
        color: '#92400e',
    },
    difficultyHard: {
        backgroundColor: '#fee2e2',
        color: '#991b1b',
    },
    purchasedBadge: {
        backgroundColor: '#dcfce7',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
        marginLeft: 'auto',
    },
    purchasedText: {
        fontSize: 11,
        color: '#166534',
        fontWeight: '600',
    },
    actionButton: {
        backgroundColor: '#6366f1',
        paddingVertical: 15,
        borderRadius: 6,
        alignItems: 'center',
        marginTop: 10,
    },
    actionButtonText: {
        color: '#ffffff',
        fontSize: 14,
        fontWeight: '600',
    },
    headerSubtitle: {
        fontSize: 13,
        color: '#6b7280',
        marginTop: 2,
    },
    emptySubtext: {
        fontSize: 14,
        color: '#6b7280',
    },
    quizCard: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        overflow: 'hidden',
        marginBottom: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    quizImage: {
        width: '100%',
        height: 120,
        backgroundColor: '#e5e7eb',
    },
    quizContent: {
        padding: 12,
    },
    quizHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 12,
        gap: 8,
    },
    quizInfo: {
        flex: 1,
    },
    quizTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#1f2937',
        marginBottom: 2,
    },
    quizCategory: {
        fontSize: 12,
        color: '#6b7280',
    },
    easyBg: {
        color: '#166534',
    },
    mediumBg: {
        color: '#92400e',
    },
    hardBg: {
        color: '#991b1b',
    },
    statsRow: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 12,
    },
    statBox: {
        flex: 1,
        backgroundColor: '#f3f4f6',
        paddingVertical: 8,
        paddingHorizontal: 6,
        borderRadius: 6,
        alignItems: 'center',
    },
    attemptsBar: {
        marginBottom: 12,
    },
    attemptsText: {
        fontSize: 12,
        color: '#6b7280',
        marginBottom: 4,
    },
    progressBar: {
        height: 6,
        backgroundColor: '#e5e7eb',
        borderRadius: 3,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        backgroundColor: '#6366f1',
    },
    startButton: {
        backgroundColor: '#6366f1',
        paddingVertical: 10,
        borderRadius: 6,
        alignItems: 'center',
    },
    startButtonText: {
        color: '#ffffff',
        fontSize: 14,
        fontWeight: '600',
    },
    userRankCard: {
        marginHorizontal: 16,
        marginVertical: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: '#ffffff',
        borderRadius: 12,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    userRankContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        flex: 1,
    },
    userRankBadge: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#dbeafe',
        justifyContent: 'center',
        alignItems: 'center',
    },
    userRankNumber: {
        fontSize: 14,
        fontWeight: '700',
        color: '#0284c7',
    },
    userRankInfo: {
        gap: 2,
    },
    userRankName: {
        fontSize: 14,
        fontWeight: '700',
        color: '#1f2937',
    },
    userRankPoints: {
        fontSize: 12,
        color: '#6b7280',
    },
    userRankMedal: {
        marginLeft: 'auto',
    },
    tabsContainer: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
        backgroundColor: '#ffffff',
    },
    tab: {
        flex: 1,
        paddingVertical: 12,
        alignItems: 'center',
    },
    activeTab: {
        borderBottomWidth: 2,
        borderBottomColor: '#6366f1',
    },
    tabText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#6b7280',
    },
    activeTabText: {
        color: '#6366f1',
    },
    packageFilter: {
        backgroundColor: '#ffffff',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
    },
    packageFilterContent: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        gap: 8,
    },
    packageFilterButton: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 6,
        backgroundColor: '#f3f4f6',
    },
    packageFilterButtonActive: {
        backgroundColor: '#6366f1',
    },
    packageFilterButtonText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6b7280',
    },
    packageFilterButtonTextActive: {
        color: '#ffffff',
    },
    currentUserItem: {
        backgroundColor: '#f0f4ff',
        borderWidth: 1,
        borderColor: '#6366f1',
    },
    rankContainer: {
        width: 40,
        alignItems: 'center',
    },
    topRankBadge: {
        backgroundColor: '#fef3c7',
    },
    rank1: {
        color: '#b45309',
    },
    rank2: {
        color: '#4b5563',
    },
    rank3: {
        color: '#a16207',
    },
    userAvatarPlaceholder: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#e5e7eb',
        justifyContent: 'center',
        alignItems: 'center',
    },
    userInfo: {
        flex: 1,
        gap: 2,
    },
    quizzesText: {
        fontSize: 12,
        color: '#6b7280',
    },
    pointsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: 8,
        paddingVertical: 4,
        backgroundColor: '#fef3c7',
        borderRadius: 4,
    },
    pointsText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#92400e',
    },
    youBadge: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        backgroundColor: '#dcfce7',
        borderRadius: 4,
    },
    youBadgeText: {
        fontSize: 11,
        fontWeight: '700',
        color: '#166534',
    },
    headerCenter: {
        flex: 1,
        marginHorizontal: 12,
    },
    timer: {
        fontSize: 14,
        fontWeight: '700',
        color: '#6366f1',
    },
    progressContainer: {
        height: 4,
        backgroundColor: '#e5e7eb',
        overflow: 'hidden',
    },
    questionSection: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    questionImage: {
        width: '100%',
        height: 200,
        borderRadius: 8,
        marginBottom: 12,
        backgroundColor: '#e5e7eb',
    },
    questionText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1f2937',
        lineHeight: 24,
    },
    answersSection: {
        gap: 12,
    },
    answersTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1f2937',
    },
    answerButton: {
        flexDirection: 'row',
        paddingHorizontal: 12,
        paddingVertical: 12,
        backgroundColor: '#ffffff',
        borderRadius: 8,
        borderWidth: 2,
        borderColor: '#e5e7eb',
        gap: 12,
        alignItems: 'flex-start',
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },
    answerButtonSelected: {
        borderColor: '#6366f1',
        backgroundColor: '#f0f4ff',
    },
    answerButtonCorrect: {
        borderColor: '#16a34a',
        backgroundColor: '#dcfce7',
    },
    answerButtonIncorrect: {
        borderColor: '#dc2626',
        backgroundColor: '#fee2e2',
    },
    answerIndicator: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#d1d5db',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 2,
    },
    answerIndicatorSelected: {
        borderColor: '#6366f1',
        backgroundColor: '#6366f1',
    },
    answerIndicatorCorrect: {
        borderColor: '#16a34a',
        backgroundColor: '#16a34a',
    },
    answerIndicatorIncorrect: {
        borderColor: '#dc2626',
        backgroundColor: '#dc2626',
    },
    answerImage: {
        width: 60,
        height: 60,
        borderRadius: 6,
        backgroundColor: '#e5e7eb',
    },
    answerContent: {
        flex: 1,
    },
    answerText: {
        fontSize: 13,
        color: '#1f2937',
        lineHeight: 18,
    },
    explanationSection: {
        backgroundColor: '#dbeafe',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 12,
        gap: 8,
        borderLeftWidth: 4,
        borderLeftColor: '#0284c7',
    },
    explanationHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    explanationTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#0284c7',
    },
    explanationText: {
        fontSize: 13,
        color: '#0c4a6e',
        lineHeight: 20,
    },
    actionButtons: {
        gap: 12,
    },
    skipButton: {
        paddingVertical: 12,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: '#d1d5db',
        alignItems: 'center',
    },
    skipButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#6b7280',
    },
    submitAnswerButton: {
        backgroundColor: '#6366f1',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    submitAnswerButtonText: {
        color: '#ffffff',
        fontSize: 14,
        fontWeight: '600',
    },
    navigationBar: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: '#ffffff',
        borderTopWidth: 1,
        borderTopColor: '#e5e7eb',
    },
    navButton: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#f3f4f6',
        justifyContent: 'center',
        alignItems: 'center',
    },
    navButtonDisabled: {
        opacity: 0.5,
    },
    scoreCard: {
        alignItems: 'center',
        backgroundColor: '#ffffff',
        borderRadius: 12,
        paddingVertical: 24,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    scoreCircle: {
        width: 140,
        height: 140,
        borderRadius: 70,
        borderWidth: 4,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    scorePercentage: {
        fontSize: 48,
        fontWeight: '700',
    },
    scoreRating: {
        fontSize: 18,
        fontWeight: '700',
    },
    statsContainer: {
        flexDirection: 'row',
        gap: 12,
    },
    statIcon: {
        marginBottom: 4,
    },
    statContent: {
        alignItems: 'center',
    },
    detailsContainer: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    detailsTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#1f2937',
        marginBottom: 12,
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
    },
    detailLeft: {
        flex: 1,
    },
    detailRight: {
        flex: 1,
    },
    detailDivider: {
        width: 1,
        height: 40,
        backgroundColor: '#e5e7eb',
    },
    feedbackContainer: {
        marginBottom: 12,
    },
    feedbackCard: {
        flexDirection: 'row',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        gap: 12,
        alignItems: 'flex-start',
    },
    feedbackContent: {
        flex: 1,
    },
    feedbackTitle: {
        fontSize: 14,
        fontWeight: '700',
        marginBottom: 4,
    },
    feedbackText: {
        fontSize: 13,
        lineHeight: 18,
    },
    actions: {
        flexDirection: 'row',
        gap: 12,
        paddingHorizontal: 16,
        paddingBottom: 16,
    },
    primaryButton: {
        flex: 1,
        flexDirection: 'row',
        backgroundColor: '#6366f1',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    primaryButtonText: {
        color: '#ffffff',
        fontSize: 14,
        fontWeight: '600',
    },
    secondaryButton: {
        flexDirection: 'row',
        borderWidth: 2,
        borderColor: '#6366f1',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
    },
    secondaryButtonText: {
        color: '#6366f1',
        fontSize: 12,
        fontWeight: '600',
    },
});